channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.3
- pip:
  - mlflow==3.5.1
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - psutil==7.1.3
  - scikit-learn==1.4.2
  - scipy==1.13.0
name: mlflow-env
